language: python

python:
  - "2.7"
  - "3.6"

env:
  matrix:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-dj100
    - TOX_ENV=py36-dj18
    - TOX_ENV=py36-dj19
    - TOX_ENV=py36-dj100
    - TOX_ENV=py36-cov

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
